In [1]:
from tensorflow.keras.preprocessing.text import one_hot

c:\CP\venv\lib\site-packages\google\api_core\_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.18) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
c:\CP\venv\lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.14.6 when it was built against 1.14.5, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "


In [22]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
## Define the vocabulary size
voc_size=10000

In [25]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [26]:
### One Hot Representation
one_hot_repr=[one_hot (words,voc_size) for words in sent]
one_hot_repr

[[9492, 9151, 6957, 811],
 [9492, 9151, 6957, 95],
 [9492, 2024, 6957, 4556],
 [9553, 6331, 3984, 3349, 6805],
 [9553, 6331, 3984, 3349, 5883],
 [9158, 9492, 2585, 6957, 9868],
 [1070, 5772, 3043, 3349]]

In [27]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding

# from tensorflow.keras.processing.sequence import pad_sequences

from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np

In [29]:
sent_length=8

embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9492 9151 6957  811]
 [   0    0    0    0 9492 9151 6957   95]
 [   0    0    0    0 9492 2024 6957 4556]
 [   0    0    0 9553 6331 3984 3349 6805]
 [   0    0    0 9553 6331 3984 3349 5883]
 [   0    0    0 9158 9492 2585 6957 9868]
 [   0    0    0    0 1070 5772 3043 3349]]


In [30]:
## feature representation
dim=10

In [31]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [53]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[[-4.80927527e-04,  2.42785700e-02,  2.40295269e-02,
         -2.76061147e-03, -2.23165881e-02, -3.41631174e-02,
          4.55073975e-02, -1.52273104e-03, -3.68465893e-02,
          2.97289826e-02],
        [-4.80927527e-04,  2.42785700e-02,  2.40295269e-02,
         -2.76061147e-03, -2.23165881e-02, -3.41631174e-02,
          4.55073975e-02, -1.52273104e-03, -3.68465893e-02,
          2.97289826e-02],
        [-4.80927527e-04,  2.42785700e-02,  2.40295269e-02,
         -2.76061147e-03, -2.23165881e-02, -3.41631174e-02,
          4.55073975e-02, -1.52273104e-03, -3.68465893e-02,
          2.97289826e-02],
        [-4.80927527e-04,  2.42785700e-02,  2.40295269e-02,
         -2.76061147e-03, -2.23165881e-02, -3.41631174e-02,
          4.55073975e-02, -1.52273104e-03, -3.68465893e-02,
          2.97289826e-02],
        [-8.17023590e-03,  4.66449186e-03, -2.27163788e-02,
         -2.70267371e-02, -4.08661254e-02,  7.92838633e-04,
          9.17768478e-03, -1.65893920e-02,  3.455504

In [54]:
embedded_docs[0]

array([   0,    0,    0,    0, 9492, 9151, 6957,  811], dtype=int32)

In [55]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[[-0.04061943,  0.01615215,  0.04051713,  0.02171798,
         -0.04969173, -0.00498693,  0.03251561,  0.02193725,
         -0.04310453, -0.04839078],
        [-0.04061943,  0.01615215,  0.04051713,  0.02171798,
         -0.04969173, -0.00498693,  0.03251561,  0.02193725,
         -0.04310453, -0.04839078],
        [-0.04061943,  0.01615215,  0.04051713,  0.02171798,
         -0.04969173, -0.00498693,  0.03251561,  0.02193725,
         -0.04310453, -0.04839078],
        [-0.04061943,  0.01615215,  0.04051713,  0.02171798,
         -0.04969173, -0.00498693,  0.03251561,  0.02193725,
         -0.04310453, -0.04839078],
        [-0.04962436, -0.02190039, -0.03320397,  0.01498288,
         -0.01492108,  0.02837719,  0.04053688,  0.03844775,
          0.01677698,  0.03707803],
        [ 0.00633083,  0.00513072, -0.0373841 , -0.01257193,
          0.04843423, -0.01888114,  0.01771415,  0.04687515,
          0.0206908 ,  0.04787813],
        [ 0.03103511, -0.02548679,  0.00794625,  0.0